### Create a new member
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "{{$random.alphabetic(12)}}",
  "email": "{{$random.email}}",
  "phone": "73689763765"
}

### Get all members
GET http://localhost:8080/members

### Get member by id
GET http://localhost:8080/members/1